// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lobby.proto

#ifndef PROTOBUF_lobby_2eproto__INCLUDED
#define PROTOBUF_lobby_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace TLMP {
namespace LobbyMessages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_lobby_2eproto();
void protobuf_AssignDesc_lobby_2eproto();
void protobuf_ShutdownFile_lobby_2eproto();

class Version;
class ClientPlayerName;
class BatchPlayerNames;
class PlayerLeft;
class ChatMessage;
class Game;
class GameID;
class HostingNewGame;
class ViewGames;
class GameInfo;

// ===================================================================

class Version : public ::google::protobuf::Message {
 public:
  Version();
  virtual ~Version();
  
  Version(const Version& from);
  
  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Version& default_instance();
  
  void Swap(Version* other);
  
  // implements Message ----------------------------------------------
  
  Version* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.Version)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 version_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Version* default_instance_;
};
// -------------------------------------------------------------------

class ClientPlayerName : public ::google::protobuf::Message {
 public:
  ClientPlayerName();
  virtual ~ClientPlayerName();
  
  ClientPlayerName(const ClientPlayerName& from);
  
  inline ClientPlayerName& operator=(const ClientPlayerName& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ClientPlayerName& default_instance();
  
  void Swap(ClientPlayerName* other);
  
  // implements Message ----------------------------------------------
  
  ClientPlayerName* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ClientPlayerName& from);
  void MergeFrom(const ClientPlayerName& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string playerName = 1;
  inline bool has_playername() const;
  inline void clear_playername();
  static const int kPlayerNameFieldNumber = 1;
  inline const ::std::string& playername() const;
  inline void set_playername(const ::std::string& value);
  inline void set_playername(const char* value);
  inline void set_playername(const char* value, size_t size);
  inline ::std::string* mutable_playername();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.ClientPlayerName)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* playername_;
  static const ::std::string _default_playername_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ClientPlayerName* default_instance_;
};
// -------------------------------------------------------------------

class BatchPlayerNames : public ::google::protobuf::Message {
 public:
  BatchPlayerNames();
  virtual ~BatchPlayerNames();
  
  BatchPlayerNames(const BatchPlayerNames& from);
  
  inline BatchPlayerNames& operator=(const BatchPlayerNames& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BatchPlayerNames& default_instance();
  
  void Swap(BatchPlayerNames* other);
  
  // implements Message ----------------------------------------------
  
  BatchPlayerNames* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BatchPlayerNames& from);
  void MergeFrom(const BatchPlayerNames& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated string playerNames = 1;
  inline int playernames_size() const;
  inline void clear_playernames();
  static const int kPlayerNamesFieldNumber = 1;
  inline const ::std::string& playernames(int index) const;
  inline ::std::string* mutable_playernames(int index);
  inline void set_playernames(int index, const ::std::string& value);
  inline void set_playernames(int index, const char* value);
  inline void set_playernames(int index, const char* value, size_t size);
  inline ::std::string* add_playernames();
  inline void add_playernames(const ::std::string& value);
  inline void add_playernames(const char* value);
  inline void add_playernames(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& playernames() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_playernames();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.BatchPlayerNames)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::std::string> playernames_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static BatchPlayerNames* default_instance_;
};
// -------------------------------------------------------------------

class PlayerLeft : public ::google::protobuf::Message {
 public:
  PlayerLeft();
  virtual ~PlayerLeft();
  
  PlayerLeft(const PlayerLeft& from);
  
  inline PlayerLeft& operator=(const PlayerLeft& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const PlayerLeft& default_instance();
  
  void Swap(PlayerLeft* other);
  
  // implements Message ----------------------------------------------
  
  PlayerLeft* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PlayerLeft& from);
  void MergeFrom(const PlayerLeft& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string playerName = 1;
  inline bool has_playername() const;
  inline void clear_playername();
  static const int kPlayerNameFieldNumber = 1;
  inline const ::std::string& playername() const;
  inline void set_playername(const ::std::string& value);
  inline void set_playername(const char* value);
  inline void set_playername(const char* value, size_t size);
  inline ::std::string* mutable_playername();
  
  // repeated string playersRemaining = 2;
  inline int playersremaining_size() const;
  inline void clear_playersremaining();
  static const int kPlayersRemainingFieldNumber = 2;
  inline const ::std::string& playersremaining(int index) const;
  inline ::std::string* mutable_playersremaining(int index);
  inline void set_playersremaining(int index, const ::std::string& value);
  inline void set_playersremaining(int index, const char* value);
  inline void set_playersremaining(int index, const char* value, size_t size);
  inline ::std::string* add_playersremaining();
  inline void add_playersremaining(const ::std::string& value);
  inline void add_playersremaining(const char* value);
  inline void add_playersremaining(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& playersremaining() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_playersremaining();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.PlayerLeft)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* playername_;
  static const ::std::string _default_playername_;
  ::google::protobuf::RepeatedPtrField< ::std::string> playersremaining_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static PlayerLeft* default_instance_;
};
// -------------------------------------------------------------------

class ChatMessage : public ::google::protobuf::Message {
 public:
  ChatMessage();
  virtual ~ChatMessage();
  
  ChatMessage(const ChatMessage& from);
  
  inline ChatMessage& operator=(const ChatMessage& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ChatMessage& default_instance();
  
  void Swap(ChatMessage* other);
  
  // implements Message ----------------------------------------------
  
  ChatMessage* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ChatMessage& from);
  void MergeFrom(const ChatMessage& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string sender = 1;
  inline bool has_sender() const;
  inline void clear_sender();
  static const int kSenderFieldNumber = 1;
  inline const ::std::string& sender() const;
  inline void set_sender(const ::std::string& value);
  inline void set_sender(const char* value);
  inline void set_sender(const char* value, size_t size);
  inline ::std::string* mutable_sender();
  
  // required string message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.ChatMessage)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* sender_;
  static const ::std::string _default_sender_;
  ::std::string* message_;
  static const ::std::string _default_message_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ChatMessage* default_instance_;
};
// -------------------------------------------------------------------

class Game : public ::google::protobuf::Message {
 public:
  Game();
  virtual ~Game();
  
  Game(const Game& from);
  
  inline Game& operator=(const Game& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Game& default_instance();
  
  void Swap(Game* other);
  
  // implements Message ----------------------------------------------
  
  Game* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Game& from);
  void MergeFrom(const Game& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // required int32 current_players = 3;
  inline bool has_current_players() const;
  inline void clear_current_players();
  static const int kCurrentPlayersFieldNumber = 3;
  inline ::google::protobuf::int32 current_players() const;
  inline void set_current_players(::google::protobuf::int32 value);
  
  // required int32 max_players = 4;
  inline bool has_max_players() const;
  inline void clear_max_players();
  static const int kMaxPlayersFieldNumber = 4;
  inline ::google::protobuf::int32 max_players() const;
  inline void set_max_players(::google::protobuf::int32 value);
  
  // required string description = 5;
  inline bool has_description() const;
  inline void clear_description();
  static const int kDescriptionFieldNumber = 5;
  inline const ::std::string& description() const;
  inline void set_description(const ::std::string& value);
  inline void set_description(const char* value);
  inline void set_description(const char* value, size_t size);
  inline ::std::string* mutable_description();
  
  // required string current_level = 6;
  inline bool has_current_level() const;
  inline void clear_current_level();
  static const int kCurrentLevelFieldNumber = 6;
  inline const ::std::string& current_level() const;
  inline void set_current_level(const ::std::string& value);
  inline void set_current_level(const char* value);
  inline void set_current_level(const char* value, size_t size);
  inline ::std::string* mutable_current_level();
  
  // required int32 port = 7;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 7;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.Game)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::google::protobuf::int32 current_players_;
  ::google::protobuf::int32 max_players_;
  ::std::string* description_;
  static const ::std::string _default_description_;
  ::std::string* current_level_;
  static const ::std::string _default_current_level_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(7 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Game* default_instance_;
};
// -------------------------------------------------------------------

class GameID : public ::google::protobuf::Message {
 public:
  GameID();
  virtual ~GameID();
  
  GameID(const GameID& from);
  
  inline GameID& operator=(const GameID& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameID& default_instance();
  
  void Swap(GameID* other);
  
  // implements Message ----------------------------------------------
  
  GameID* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameID& from);
  void MergeFrom(const GameID& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.GameID)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameID* default_instance_;
};
// -------------------------------------------------------------------

class HostingNewGame : public ::google::protobuf::Message {
 public:
  HostingNewGame();
  virtual ~HostingNewGame();
  
  HostingNewGame(const HostingNewGame& from);
  
  inline HostingNewGame& operator=(const HostingNewGame& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const HostingNewGame& default_instance();
  
  void Swap(HostingNewGame* other);
  
  // implements Message ----------------------------------------------
  
  HostingNewGame* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const HostingNewGame& from);
  void MergeFrom(const HostingNewGame& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required .TLMP.LobbyMessages.Game game = 1;
  inline bool has_game() const;
  inline void clear_game();
  static const int kGameFieldNumber = 1;
  inline const ::TLMP::LobbyMessages::Game& game() const;
  inline ::TLMP::LobbyMessages::Game* mutable_game();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.HostingNewGame)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::TLMP::LobbyMessages::Game* game_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static HostingNewGame* default_instance_;
};
// -------------------------------------------------------------------

class ViewGames : public ::google::protobuf::Message {
 public:
  ViewGames();
  virtual ~ViewGames();
  
  ViewGames(const ViewGames& from);
  
  inline ViewGames& operator=(const ViewGames& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ViewGames& default_instance();
  
  void Swap(ViewGames* other);
  
  // implements Message ----------------------------------------------
  
  ViewGames* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ViewGames& from);
  void MergeFrom(const ViewGames& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .TLMP.LobbyMessages.Game games = 1;
  inline int games_size() const;
  inline void clear_games();
  static const int kGamesFieldNumber = 1;
  inline const ::TLMP::LobbyMessages::Game& games(int index) const;
  inline ::TLMP::LobbyMessages::Game* mutable_games(int index);
  inline ::TLMP::LobbyMessages::Game* add_games();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::LobbyMessages::Game >&
      games() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::LobbyMessages::Game >*
      mutable_games();
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.ViewGames)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::TLMP::LobbyMessages::Game > games_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ViewGames* default_instance_;
};
// -------------------------------------------------------------------

class GameInfo : public ::google::protobuf::Message {
 public:
  GameInfo();
  virtual ~GameInfo();
  
  GameInfo(const GameInfo& from);
  
  inline GameInfo& operator=(const GameInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameInfo& default_instance();
  
  void Swap(GameInfo* other);
  
  // implements Message ----------------------------------------------
  
  GameInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameInfo& from);
  void MergeFrom(const GameInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required string host_name = 1;
  inline bool has_host_name() const;
  inline void clear_host_name();
  static const int kHostNameFieldNumber = 1;
  inline const ::std::string& host_name() const;
  inline void set_host_name(const ::std::string& value);
  inline void set_host_name(const char* value);
  inline void set_host_name(const char* value, size_t size);
  inline ::std::string* mutable_host_name();
  
  // required int32 port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.LobbyMessages.GameInfo)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::std::string* host_name_;
  static const ::std::string _default_host_name_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_lobby_2eproto();
  friend void protobuf_AssignDesc_lobby_2eproto();
  friend void protobuf_ShutdownFile_lobby_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameInfo* default_instance_;
};
// ===================================================================


// ===================================================================

// Version

// required int32 version = 1;
inline bool Version::has_version() const {
  return _has_bit(0);
}
inline void Version::clear_version() {
  version_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Version::version() const {
  return version_;
}
inline void Version::set_version(::google::protobuf::int32 value) {
  _set_bit(0);
  version_ = value;
}

// -------------------------------------------------------------------

// ClientPlayerName

// required string playerName = 1;
inline bool ClientPlayerName::has_playername() const {
  return _has_bit(0);
}
inline void ClientPlayerName::clear_playername() {
  if (playername_ != &_default_playername_) {
    playername_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& ClientPlayerName::playername() const {
  return *playername_;
}
inline void ClientPlayerName::set_playername(const ::std::string& value) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(value);
}
inline void ClientPlayerName::set_playername(const char* value) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(value);
}
inline void ClientPlayerName::set_playername(const char* value, size_t size) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ClientPlayerName::mutable_playername() {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  return playername_;
}

// -------------------------------------------------------------------

// BatchPlayerNames

// repeated string playerNames = 1;
inline int BatchPlayerNames::playernames_size() const {
  return playernames_.size();
}
inline void BatchPlayerNames::clear_playernames() {
  playernames_.Clear();
}
inline const ::std::string& BatchPlayerNames::playernames(int index) const {
  return playernames_.Get(index);
}
inline ::std::string* BatchPlayerNames::mutable_playernames(int index) {
  return playernames_.Mutable(index);
}
inline void BatchPlayerNames::set_playernames(int index, const ::std::string& value) {
  playernames_.Mutable(index)->assign(value);
}
inline void BatchPlayerNames::set_playernames(int index, const char* value) {
  playernames_.Mutable(index)->assign(value);
}
inline void BatchPlayerNames::set_playernames(int index, const char* value, size_t size) {
  playernames_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* BatchPlayerNames::add_playernames() {
  return playernames_.Add();
}
inline void BatchPlayerNames::add_playernames(const ::std::string& value) {
  playernames_.Add()->assign(value);
}
inline void BatchPlayerNames::add_playernames(const char* value) {
  playernames_.Add()->assign(value);
}
inline void BatchPlayerNames::add_playernames(const char* value, size_t size) {
  playernames_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
BatchPlayerNames::playernames() const {
  return playernames_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
BatchPlayerNames::mutable_playernames() {
  return &playernames_;
}

// -------------------------------------------------------------------

// PlayerLeft

// required string playerName = 1;
inline bool PlayerLeft::has_playername() const {
  return _has_bit(0);
}
inline void PlayerLeft::clear_playername() {
  if (playername_ != &_default_playername_) {
    playername_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& PlayerLeft::playername() const {
  return *playername_;
}
inline void PlayerLeft::set_playername(const ::std::string& value) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(value);
}
inline void PlayerLeft::set_playername(const char* value) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(value);
}
inline void PlayerLeft::set_playername(const char* value, size_t size) {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  playername_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerLeft::mutable_playername() {
  _set_bit(0);
  if (playername_ == &_default_playername_) {
    playername_ = new ::std::string;
  }
  return playername_;
}

// repeated string playersRemaining = 2;
inline int PlayerLeft::playersremaining_size() const {
  return playersremaining_.size();
}
inline void PlayerLeft::clear_playersremaining() {
  playersremaining_.Clear();
}
inline const ::std::string& PlayerLeft::playersremaining(int index) const {
  return playersremaining_.Get(index);
}
inline ::std::string* PlayerLeft::mutable_playersremaining(int index) {
  return playersremaining_.Mutable(index);
}
inline void PlayerLeft::set_playersremaining(int index, const ::std::string& value) {
  playersremaining_.Mutable(index)->assign(value);
}
inline void PlayerLeft::set_playersremaining(int index, const char* value) {
  playersremaining_.Mutable(index)->assign(value);
}
inline void PlayerLeft::set_playersremaining(int index, const char* value, size_t size) {
  playersremaining_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
}
inline ::std::string* PlayerLeft::add_playersremaining() {
  return playersremaining_.Add();
}
inline void PlayerLeft::add_playersremaining(const ::std::string& value) {
  playersremaining_.Add()->assign(value);
}
inline void PlayerLeft::add_playersremaining(const char* value) {
  playersremaining_.Add()->assign(value);
}
inline void PlayerLeft::add_playersremaining(const char* value, size_t size) {
  playersremaining_.Add()->assign(reinterpret_cast<const char*>(value), size);
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
PlayerLeft::playersremaining() const {
  return playersremaining_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
PlayerLeft::mutable_playersremaining() {
  return &playersremaining_;
}

// -------------------------------------------------------------------

// ChatMessage

// required string sender = 1;
inline bool ChatMessage::has_sender() const {
  return _has_bit(0);
}
inline void ChatMessage::clear_sender() {
  if (sender_ != &_default_sender_) {
    sender_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& ChatMessage::sender() const {
  return *sender_;
}
inline void ChatMessage::set_sender(const ::std::string& value) {
  _set_bit(0);
  if (sender_ == &_default_sender_) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void ChatMessage::set_sender(const char* value) {
  _set_bit(0);
  if (sender_ == &_default_sender_) {
    sender_ = new ::std::string;
  }
  sender_->assign(value);
}
inline void ChatMessage::set_sender(const char* value, size_t size) {
  _set_bit(0);
  if (sender_ == &_default_sender_) {
    sender_ = new ::std::string;
  }
  sender_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_sender() {
  _set_bit(0);
  if (sender_ == &_default_sender_) {
    sender_ = new ::std::string;
  }
  return sender_;
}

// required string message = 2;
inline bool ChatMessage::has_message() const {
  return _has_bit(1);
}
inline void ChatMessage::clear_message() {
  if (message_ != &_default_message_) {
    message_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& ChatMessage::message() const {
  return *message_;
}
inline void ChatMessage::set_message(const ::std::string& value) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void ChatMessage::set_message(const char* value) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(value);
}
inline void ChatMessage::set_message(const char* value, size_t size) {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ChatMessage::mutable_message() {
  _set_bit(1);
  if (message_ == &_default_message_) {
    message_ = new ::std::string;
  }
  return message_;
}

// -------------------------------------------------------------------

// Game

// required int32 id = 1;
inline bool Game::has_id() const {
  return _has_bit(0);
}
inline void Game::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Game::id() const {
  return id_;
}
inline void Game::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required string name = 2;
inline bool Game::has_name() const {
  return _has_bit(1);
}
inline void Game::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Game::name() const {
  return *name_;
}
inline void Game::set_name(const ::std::string& value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Game::set_name(const char* value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Game::set_name(const char* value, size_t size) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Game::mutable_name() {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// required int32 current_players = 3;
inline bool Game::has_current_players() const {
  return _has_bit(2);
}
inline void Game::clear_current_players() {
  current_players_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 Game::current_players() const {
  return current_players_;
}
inline void Game::set_current_players(::google::protobuf::int32 value) {
  _set_bit(2);
  current_players_ = value;
}

// required int32 max_players = 4;
inline bool Game::has_max_players() const {
  return _has_bit(3);
}
inline void Game::clear_max_players() {
  max_players_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 Game::max_players() const {
  return max_players_;
}
inline void Game::set_max_players(::google::protobuf::int32 value) {
  _set_bit(3);
  max_players_ = value;
}

// required string description = 5;
inline bool Game::has_description() const {
  return _has_bit(4);
}
inline void Game::clear_description() {
  if (description_ != &_default_description_) {
    description_->clear();
  }
  _clear_bit(4);
}
inline const ::std::string& Game::description() const {
  return *description_;
}
inline void Game::set_description(const ::std::string& value) {
  _set_bit(4);
  if (description_ == &_default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Game::set_description(const char* value) {
  _set_bit(4);
  if (description_ == &_default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(value);
}
inline void Game::set_description(const char* value, size_t size) {
  _set_bit(4);
  if (description_ == &_default_description_) {
    description_ = new ::std::string;
  }
  description_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Game::mutable_description() {
  _set_bit(4);
  if (description_ == &_default_description_) {
    description_ = new ::std::string;
  }
  return description_;
}

// required string current_level = 6;
inline bool Game::has_current_level() const {
  return _has_bit(5);
}
inline void Game::clear_current_level() {
  if (current_level_ != &_default_current_level_) {
    current_level_->clear();
  }
  _clear_bit(5);
}
inline const ::std::string& Game::current_level() const {
  return *current_level_;
}
inline void Game::set_current_level(const ::std::string& value) {
  _set_bit(5);
  if (current_level_ == &_default_current_level_) {
    current_level_ = new ::std::string;
  }
  current_level_->assign(value);
}
inline void Game::set_current_level(const char* value) {
  _set_bit(5);
  if (current_level_ == &_default_current_level_) {
    current_level_ = new ::std::string;
  }
  current_level_->assign(value);
}
inline void Game::set_current_level(const char* value, size_t size) {
  _set_bit(5);
  if (current_level_ == &_default_current_level_) {
    current_level_ = new ::std::string;
  }
  current_level_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Game::mutable_current_level() {
  _set_bit(5);
  if (current_level_ == &_default_current_level_) {
    current_level_ = new ::std::string;
  }
  return current_level_;
}

// required int32 port = 7;
inline bool Game::has_port() const {
  return _has_bit(6);
}
inline void Game::clear_port() {
  port_ = 0;
  _clear_bit(6);
}
inline ::google::protobuf::int32 Game::port() const {
  return port_;
}
inline void Game::set_port(::google::protobuf::int32 value) {
  _set_bit(6);
  port_ = value;
}

// -------------------------------------------------------------------

// GameID

// required int32 id = 1;
inline bool GameID::has_id() const {
  return _has_bit(0);
}
inline void GameID::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 GameID::id() const {
  return id_;
}
inline void GameID::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// -------------------------------------------------------------------

// HostingNewGame

// required .TLMP.LobbyMessages.Game game = 1;
inline bool HostingNewGame::has_game() const {
  return _has_bit(0);
}
inline void HostingNewGame::clear_game() {
  if (game_ != NULL) game_->::TLMP::LobbyMessages::Game::Clear();
  _clear_bit(0);
}
inline const ::TLMP::LobbyMessages::Game& HostingNewGame::game() const {
  return game_ != NULL ? *game_ : *default_instance_->game_;
}
inline ::TLMP::LobbyMessages::Game* HostingNewGame::mutable_game() {
  _set_bit(0);
  if (game_ == NULL) game_ = new ::TLMP::LobbyMessages::Game;
  return game_;
}

// -------------------------------------------------------------------

// ViewGames

// repeated .TLMP.LobbyMessages.Game games = 1;
inline int ViewGames::games_size() const {
  return games_.size();
}
inline void ViewGames::clear_games() {
  games_.Clear();
}
inline const ::TLMP::LobbyMessages::Game& ViewGames::games(int index) const {
  return games_.Get(index);
}
inline ::TLMP::LobbyMessages::Game* ViewGames::mutable_games(int index) {
  return games_.Mutable(index);
}
inline ::TLMP::LobbyMessages::Game* ViewGames::add_games() {
  return games_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::LobbyMessages::Game >&
ViewGames::games() const {
  return games_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::LobbyMessages::Game >*
ViewGames::mutable_games() {
  return &games_;
}

// -------------------------------------------------------------------

// GameInfo

// required string host_name = 1;
inline bool GameInfo::has_host_name() const {
  return _has_bit(0);
}
inline void GameInfo::clear_host_name() {
  if (host_name_ != &_default_host_name_) {
    host_name_->clear();
  }
  _clear_bit(0);
}
inline const ::std::string& GameInfo::host_name() const {
  return *host_name_;
}
inline void GameInfo::set_host_name(const ::std::string& value) {
  _set_bit(0);
  if (host_name_ == &_default_host_name_) {
    host_name_ = new ::std::string;
  }
  host_name_->assign(value);
}
inline void GameInfo::set_host_name(const char* value) {
  _set_bit(0);
  if (host_name_ == &_default_host_name_) {
    host_name_ = new ::std::string;
  }
  host_name_->assign(value);
}
inline void GameInfo::set_host_name(const char* value, size_t size) {
  _set_bit(0);
  if (host_name_ == &_default_host_name_) {
    host_name_ = new ::std::string;
  }
  host_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* GameInfo::mutable_host_name() {
  _set_bit(0);
  if (host_name_ == &_default_host_name_) {
    host_name_ = new ::std::string;
  }
  return host_name_;
}

// required int32 port = 2;
inline bool GameInfo::has_port() const {
  return _has_bit(1);
}
inline void GameInfo::clear_port() {
  port_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 GameInfo::port() const {
  return port_;
}
inline void GameInfo::set_port(::google::protobuf::int32 value) {
  _set_bit(1);
  port_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace LobbyMessages
}  // namespace TLMP

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_lobby_2eproto__INCLUDED
