// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

#ifndef PROTOBUF_network_2eproto__INCLUDED
#define PROTOBUF_network_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace TLMP {
namespace NetworkMessages {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_network_2eproto();
void protobuf_AssignDesc_network_2eproto();
void protobuf_ShutdownFile_network_2eproto();

class Position;
class Character;
class Equipment;
class Version;
class GameHasStarted;
class GameStarted;
class GameEnded;
class GameEnter;
class GameExited;
class RequestCharacterInfo;
class ReplyCharacterInfo;
class ReplyCharacterId;
class CharacterDestination;
class Entity;
class Item;
class ItemDrop;
class ItemPickup;
class ItemEquip;
class ItemUnequip;

// ===================================================================

class Position : public ::google::protobuf::Message {
 public:
  Position();
  virtual ~Position();
  
  Position(const Position& from);
  
  inline Position& operator=(const Position& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Position& default_instance();
  
  void Swap(Position* other);
  
  // implements Message ----------------------------------------------
  
  Position* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Position& from);
  void MergeFrom(const Position& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required float x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline float x() const;
  inline void set_x(float value);
  
  // required float y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline float y() const;
  inline void set_y(float value);
  
  // required float z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline float z() const;
  inline void set_z(float value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Position)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  float x_;
  float y_;
  float z_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Position* default_instance_;
};
// -------------------------------------------------------------------

class Character : public ::google::protobuf::Message {
 public:
  Character();
  virtual ~Character();
  
  Character(const Character& from);
  
  inline Character& operator=(const Character& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Character& default_instance();
  
  void Swap(Character* other);
  
  // implements Message ----------------------------------------------
  
  Character* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Character& from);
  void MergeFrom(const Character& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);
  
  // required string name = 2;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 2;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  
  // repeated .TLMP.NetworkMessages.Character minion = 3;
  inline int minion_size() const;
  inline void clear_minion();
  static const int kMinionFieldNumber = 3;
  inline const ::TLMP::NetworkMessages::Character& minion(int index) const;
  inline ::TLMP::NetworkMessages::Character* mutable_minion(int index);
  inline ::TLMP::NetworkMessages::Character* add_minion();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >&
      minion() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >*
      mutable_minion();
  
  // repeated .TLMP.NetworkMessages.Position position = 4;
  inline int position_size() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 4;
  inline const ::TLMP::NetworkMessages::Position& position(int index) const;
  inline ::TLMP::NetworkMessages::Position* mutable_position(int index);
  inline ::TLMP::NetworkMessages::Position* add_position();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
      position() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
      mutable_position();
  
  // optional int32 id = 5;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 5;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Character)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int64 guid_;
  ::std::string* name_;
  static const ::std::string _default_name_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character > minion_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position > position_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Character* default_instance_;
};
// -------------------------------------------------------------------

class Equipment : public ::google::protobuf::Message {
 public:
  Equipment();
  virtual ~Equipment();
  
  Equipment(const Equipment& from);
  
  inline Equipment& operator=(const Equipment& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Equipment& default_instance();
  
  void Swap(Equipment* other);
  
  // implements Message ----------------------------------------------
  
  Equipment* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Equipment& from);
  void MergeFrom(const Equipment& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int64 guid = 1;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 1;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);
  
  // optional int32 slot = 2;
  inline bool has_slot() const;
  inline void clear_slot();
  static const int kSlotFieldNumber = 2;
  inline ::google::protobuf::int32 slot() const;
  inline void set_slot(::google::protobuf::int32 value);
  
  // required int32 id = 3;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 3;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Equipment)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 slot_;
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Equipment* default_instance_;
};
// -------------------------------------------------------------------

class Version : public ::google::protobuf::Message {
 public:
  Version();
  virtual ~Version();
  
  Version(const Version& from);
  
  inline Version& operator=(const Version& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Version& default_instance();
  
  void Swap(Version* other);
  
  // implements Message ----------------------------------------------
  
  Version* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Version& from);
  void MergeFrom(const Version& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 version = 1;
  inline bool has_version() const;
  inline void clear_version();
  static const int kVersionFieldNumber = 1;
  inline ::google::protobuf::int32 version() const;
  inline void set_version(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Version)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 version_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Version* default_instance_;
};
// -------------------------------------------------------------------

class GameHasStarted : public ::google::protobuf::Message {
 public:
  GameHasStarted();
  virtual ~GameHasStarted();
  
  GameHasStarted(const GameHasStarted& from);
  
  inline GameHasStarted& operator=(const GameHasStarted& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameHasStarted& default_instance();
  
  void Swap(GameHasStarted* other);
  
  // implements Message ----------------------------------------------
  
  GameHasStarted* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameHasStarted& from);
  void MergeFrom(const GameHasStarted& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required bool started = 1;
  inline bool has_started() const;
  inline void clear_started();
  static const int kStartedFieldNumber = 1;
  inline bool started() const;
  inline void set_started(bool value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.GameHasStarted)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  bool started_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameHasStarted* default_instance_;
};
// -------------------------------------------------------------------

class GameStarted : public ::google::protobuf::Message {
 public:
  GameStarted();
  virtual ~GameStarted();
  
  GameStarted(const GameStarted& from);
  
  inline GameStarted& operator=(const GameStarted& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameStarted& default_instance();
  
  void Swap(GameStarted* other);
  
  // implements Message ----------------------------------------------
  
  GameStarted* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameStarted& from);
  void MergeFrom(const GameStarted& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.GameStarted)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[1];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameStarted* default_instance_;
};
// -------------------------------------------------------------------

class GameEnded : public ::google::protobuf::Message {
 public:
  GameEnded();
  virtual ~GameEnded();
  
  GameEnded(const GameEnded& from);
  
  inline GameEnded& operator=(const GameEnded& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameEnded& default_instance();
  
  void Swap(GameEnded* other);
  
  // implements Message ----------------------------------------------
  
  GameEnded* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameEnded& from);
  void MergeFrom(const GameEnded& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.GameEnded)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[1];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameEnded* default_instance_;
};
// -------------------------------------------------------------------

class GameEnter : public ::google::protobuf::Message {
 public:
  GameEnter();
  virtual ~GameEnter();
  
  GameEnter(const GameEnter& from);
  
  inline GameEnter& operator=(const GameEnter& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameEnter& default_instance();
  
  void Swap(GameEnter* other);
  
  // implements Message ----------------------------------------------
  
  GameEnter* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameEnter& from);
  void MergeFrom(const GameEnter& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.GameEnter)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[1];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameEnter* default_instance_;
};
// -------------------------------------------------------------------

class GameExited : public ::google::protobuf::Message {
 public:
  GameExited();
  virtual ~GameExited();
  
  GameExited(const GameExited& from);
  
  inline GameExited& operator=(const GameExited& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const GameExited& default_instance();
  
  void Swap(GameExited* other);
  
  // implements Message ----------------------------------------------
  
  GameExited* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GameExited& from);
  void MergeFrom(const GameExited& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.GameExited)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[1];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static GameExited* default_instance_;
};
// -------------------------------------------------------------------

class RequestCharacterInfo : public ::google::protobuf::Message {
 public:
  RequestCharacterInfo();
  virtual ~RequestCharacterInfo();
  
  RequestCharacterInfo(const RequestCharacterInfo& from);
  
  inline RequestCharacterInfo& operator=(const RequestCharacterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestCharacterInfo& default_instance();
  
  void Swap(RequestCharacterInfo* other);
  
  // implements Message ----------------------------------------------
  
  RequestCharacterInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestCharacterInfo& from);
  void MergeFrom(const RequestCharacterInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.RequestCharacterInfo)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[1];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static RequestCharacterInfo* default_instance_;
};
// -------------------------------------------------------------------

class ReplyCharacterInfo : public ::google::protobuf::Message {
 public:
  ReplyCharacterInfo();
  virtual ~ReplyCharacterInfo();
  
  ReplyCharacterInfo(const ReplyCharacterInfo& from);
  
  inline ReplyCharacterInfo& operator=(const ReplyCharacterInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReplyCharacterInfo& default_instance();
  
  void Swap(ReplyCharacterInfo* other);
  
  // implements Message ----------------------------------------------
  
  ReplyCharacterInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReplyCharacterInfo& from);
  void MergeFrom(const ReplyCharacterInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .TLMP.NetworkMessages.Character player = 1;
  inline int player_size() const;
  inline void clear_player();
  static const int kPlayerFieldNumber = 1;
  inline const ::TLMP::NetworkMessages::Character& player(int index) const;
  inline ::TLMP::NetworkMessages::Character* mutable_player(int index);
  inline ::TLMP::NetworkMessages::Character* add_player();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >&
      player() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >*
      mutable_player();
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ReplyCharacterInfo)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character > player_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ReplyCharacterInfo* default_instance_;
};
// -------------------------------------------------------------------

class ReplyCharacterId : public ::google::protobuf::Message {
 public:
  ReplyCharacterId();
  virtual ~ReplyCharacterId();
  
  ReplyCharacterId(const ReplyCharacterId& from);
  
  inline ReplyCharacterId& operator=(const ReplyCharacterId& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ReplyCharacterId& default_instance();
  
  void Swap(ReplyCharacterId* other);
  
  // implements Message ----------------------------------------------
  
  ReplyCharacterId* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ReplyCharacterId& from);
  void MergeFrom(const ReplyCharacterId& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ReplyCharacterId)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ReplyCharacterId* default_instance_;
};
// -------------------------------------------------------------------

class CharacterDestination : public ::google::protobuf::Message {
 public:
  CharacterDestination();
  virtual ~CharacterDestination();
  
  CharacterDestination(const CharacterDestination& from);
  
  inline CharacterDestination& operator=(const CharacterDestination& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CharacterDestination& default_instance();
  
  void Swap(CharacterDestination* other);
  
  // implements Message ----------------------------------------------
  
  CharacterDestination* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CharacterDestination& from);
  void MergeFrom(const CharacterDestination& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // repeated .TLMP.NetworkMessages.Position current = 2;
  inline int current_size() const;
  inline void clear_current();
  static const int kCurrentFieldNumber = 2;
  inline const ::TLMP::NetworkMessages::Position& current(int index) const;
  inline ::TLMP::NetworkMessages::Position* mutable_current(int index);
  inline ::TLMP::NetworkMessages::Position* add_current();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
      current() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
      mutable_current();
  
  // repeated .TLMP.NetworkMessages.Position destination = 3;
  inline int destination_size() const;
  inline void clear_destination();
  static const int kDestinationFieldNumber = 3;
  inline const ::TLMP::NetworkMessages::Position& destination(int index) const;
  inline ::TLMP::NetworkMessages::Position* mutable_destination(int index);
  inline ::TLMP::NetworkMessages::Position* add_destination();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
      destination() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
      mutable_destination();
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.CharacterDestination)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position > current_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position > destination_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static CharacterDestination* default_instance_;
};
// -------------------------------------------------------------------

class Entity : public ::google::protobuf::Message {
 public:
  Entity();
  virtual ~Entity();
  
  Entity(const Entity& from);
  
  inline Entity& operator=(const Entity& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Entity& default_instance();
  
  void Swap(Entity* other);
  
  // implements Message ----------------------------------------------
  
  Entity* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Entity& from);
  void MergeFrom(const Entity& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 level = 2;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 2;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);
  
  // required int64 guid = 3;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 3;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);
  
  // required bool noItems = 4;
  inline bool has_noitems() const;
  inline void clear_noitems();
  static const int kNoItemsFieldNumber = 4;
  inline bool noitems() const;
  inline void set_noitems(bool value);
  
  // optional .TLMP.NetworkMessages.Position destination = 5;
  inline bool has_destination() const;
  inline void clear_destination();
  static const int kDestinationFieldNumber = 5;
  inline const ::TLMP::NetworkMessages::Position& destination() const;
  inline ::TLMP::NetworkMessages::Position* mutable_destination();
  
  // repeated .TLMP.NetworkMessages.Position position = 6;
  inline int position_size() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 6;
  inline const ::TLMP::NetworkMessages::Position& position(int index) const;
  inline ::TLMP::NetworkMessages::Position* mutable_position(int index);
  inline ::TLMP::NetworkMessages::Position* add_position();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
      position() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
      mutable_position();
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Entity)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int64 guid_;
  bool noitems_;
  ::TLMP::NetworkMessages::Position* destination_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position > position_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(6 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Entity* default_instance_;
};
// -------------------------------------------------------------------

class Item : public ::google::protobuf::Message {
 public:
  Item();
  virtual ~Item();
  
  Item(const Item& from);
  
  inline Item& operator=(const Item& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const Item& default_instance();
  
  void Swap(Item* other);
  
  // implements Message ----------------------------------------------
  
  Item* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Item& from);
  void MergeFrom(const Item& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int64 guid = 2;
  inline bool has_guid() const;
  inline void clear_guid();
  static const int kGuidFieldNumber = 2;
  inline ::google::protobuf::int64 guid() const;
  inline void set_guid(::google::protobuf::int64 value);
  
  // required int32 level = 3;
  inline bool has_level() const;
  inline void clear_level();
  static const int kLevelFieldNumber = 3;
  inline ::google::protobuf::int32 level() const;
  inline void set_level(::google::protobuf::int32 value);
  
  // required int32 unk0 = 4;
  inline bool has_unk0() const;
  inline void clear_unk0();
  static const int kUnk0FieldNumber = 4;
  inline ::google::protobuf::int32 unk0() const;
  inline void set_unk0(::google::protobuf::int32 value);
  
  // required int32 unk1 = 5;
  inline bool has_unk1() const;
  inline void clear_unk1();
  static const int kUnk1FieldNumber = 5;
  inline ::google::protobuf::int32 unk1() const;
  inline void set_unk1(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.Item)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int64 guid_;
  ::google::protobuf::int32 level_;
  ::google::protobuf::int32 unk0_;
  ::google::protobuf::int32 unk1_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static Item* default_instance_;
};
// -------------------------------------------------------------------

class ItemDrop : public ::google::protobuf::Message {
 public:
  ItemDrop();
  virtual ~ItemDrop();
  
  ItemDrop(const ItemDrop& from);
  
  inline ItemDrop& operator=(const ItemDrop& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemDrop& default_instance();
  
  void Swap(ItemDrop* other);
  
  // implements Message ----------------------------------------------
  
  ItemDrop* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemDrop& from);
  void MergeFrom(const ItemDrop& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // repeated .TLMP.NetworkMessages.Position position = 2;
  inline int position_size() const;
  inline void clear_position();
  static const int kPositionFieldNumber = 2;
  inline const ::TLMP::NetworkMessages::Position& position(int index) const;
  inline ::TLMP::NetworkMessages::Position* mutable_position(int index);
  inline ::TLMP::NetworkMessages::Position* add_position();
  inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
      position() const;
  inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
      mutable_position();
  
  // required bool unk0 = 3;
  inline bool has_unk0() const;
  inline void clear_unk0();
  static const int kUnk0FieldNumber = 3;
  inline bool unk0() const;
  inline void set_unk0(bool value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ItemDrop)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position > position_;
  bool unk0_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ItemDrop* default_instance_;
};
// -------------------------------------------------------------------

class ItemPickup : public ::google::protobuf::Message {
 public:
  ItemPickup();
  virtual ~ItemPickup();
  
  ItemPickup(const ItemPickup& from);
  
  inline ItemPickup& operator=(const ItemPickup& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemPickup& default_instance();
  
  void Swap(ItemPickup* other);
  
  // implements Message ----------------------------------------------
  
  ItemPickup* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemPickup& from);
  void MergeFrom(const ItemPickup& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 ownerId = 2;
  inline bool has_ownerid() const;
  inline void clear_ownerid();
  static const int kOwnerIdFieldNumber = 2;
  inline ::google::protobuf::int32 ownerid() const;
  inline void set_ownerid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ItemPickup)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 ownerid_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ItemPickup* default_instance_;
};
// -------------------------------------------------------------------

class ItemEquip : public ::google::protobuf::Message {
 public:
  ItemEquip();
  virtual ~ItemEquip();
  
  ItemEquip(const ItemEquip& from);
  
  inline ItemEquip& operator=(const ItemEquip& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemEquip& default_instance();
  
  void Swap(ItemEquip* other);
  
  // implements Message ----------------------------------------------
  
  ItemEquip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemEquip& from);
  void MergeFrom(const ItemEquip& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 slot = 2;
  inline bool has_slot() const;
  inline void clear_slot();
  static const int kSlotFieldNumber = 2;
  inline ::google::protobuf::int32 slot() const;
  inline void set_slot(::google::protobuf::int32 value);
  
  // required int32 ownerId = 3;
  inline bool has_ownerid() const;
  inline void clear_ownerid();
  static const int kOwnerIdFieldNumber = 3;
  inline ::google::protobuf::int32 ownerid() const;
  inline void set_ownerid(::google::protobuf::int32 value);
  
  // required int32 unk = 4;
  inline bool has_unk() const;
  inline void clear_unk();
  static const int kUnkFieldNumber = 4;
  inline ::google::protobuf::int32 unk() const;
  inline void set_unk(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ItemEquip)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 slot_;
  ::google::protobuf::int32 ownerid_;
  ::google::protobuf::int32 unk_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ItemEquip* default_instance_;
};
// -------------------------------------------------------------------

class ItemUnequip : public ::google::protobuf::Message {
 public:
  ItemUnequip();
  virtual ~ItemUnequip();
  
  ItemUnequip(const ItemUnequip& from);
  
  inline ItemUnequip& operator=(const ItemUnequip& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const ItemUnequip& default_instance();
  
  void Swap(ItemUnequip* other);
  
  // implements Message ----------------------------------------------
  
  ItemUnequip* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ItemUnequip& from);
  void MergeFrom(const ItemUnequip& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // required int32 ownerid = 2;
  inline bool has_ownerid() const;
  inline void clear_ownerid();
  static const int kOwneridFieldNumber = 2;
  inline ::google::protobuf::int32 ownerid() const;
  inline void set_ownerid(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:TLMP.NetworkMessages.ItemUnequip)
 private:
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  mutable int _cached_size_;
  
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 ownerid_;
  friend void  protobuf_AddDesc_network_2eproto();
  friend void protobuf_AssignDesc_network_2eproto();
  friend void protobuf_ShutdownFile_network_2eproto();
  
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  // WHY DOES & HAVE LOWER PRECEDENCE THAN != !?
  inline bool _has_bit(int index) const {
    return (_has_bits_[index / 32] & (1u << (index % 32))) != 0;
  }
  inline void _set_bit(int index) {
    _has_bits_[index / 32] |= (1u << (index % 32));
  }
  inline void _clear_bit(int index) {
    _has_bits_[index / 32] &= ~(1u << (index % 32));
  }
  
  void InitAsDefaultInstance();
  static ItemUnequip* default_instance_;
};
// ===================================================================


// ===================================================================

// Position

// required float x = 1;
inline bool Position::has_x() const {
  return _has_bit(0);
}
inline void Position::clear_x() {
  x_ = 0;
  _clear_bit(0);
}
inline float Position::x() const {
  return x_;
}
inline void Position::set_x(float value) {
  _set_bit(0);
  x_ = value;
}

// required float y = 2;
inline bool Position::has_y() const {
  return _has_bit(1);
}
inline void Position::clear_y() {
  y_ = 0;
  _clear_bit(1);
}
inline float Position::y() const {
  return y_;
}
inline void Position::set_y(float value) {
  _set_bit(1);
  y_ = value;
}

// required float z = 3;
inline bool Position::has_z() const {
  return _has_bit(2);
}
inline void Position::clear_z() {
  z_ = 0;
  _clear_bit(2);
}
inline float Position::z() const {
  return z_;
}
inline void Position::set_z(float value) {
  _set_bit(2);
  z_ = value;
}

// -------------------------------------------------------------------

// Character

// required int64 guid = 1;
inline bool Character::has_guid() const {
  return _has_bit(0);
}
inline void Character::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  _clear_bit(0);
}
inline ::google::protobuf::int64 Character::guid() const {
  return guid_;
}
inline void Character::set_guid(::google::protobuf::int64 value) {
  _set_bit(0);
  guid_ = value;
}

// required string name = 2;
inline bool Character::has_name() const {
  return _has_bit(1);
}
inline void Character::clear_name() {
  if (name_ != &_default_name_) {
    name_->clear();
  }
  _clear_bit(1);
}
inline const ::std::string& Character::name() const {
  return *name_;
}
inline void Character::set_name(const ::std::string& value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Character::set_name(const char* value) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Character::set_name(const char* value, size_t size) {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Character::mutable_name() {
  _set_bit(1);
  if (name_ == &_default_name_) {
    name_ = new ::std::string;
  }
  return name_;
}

// repeated .TLMP.NetworkMessages.Character minion = 3;
inline int Character::minion_size() const {
  return minion_.size();
}
inline void Character::clear_minion() {
  minion_.Clear();
}
inline const ::TLMP::NetworkMessages::Character& Character::minion(int index) const {
  return minion_.Get(index);
}
inline ::TLMP::NetworkMessages::Character* Character::mutable_minion(int index) {
  return minion_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Character* Character::add_minion() {
  return minion_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >&
Character::minion() const {
  return minion_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >*
Character::mutable_minion() {
  return &minion_;
}

// repeated .TLMP.NetworkMessages.Position position = 4;
inline int Character::position_size() const {
  return position_.size();
}
inline void Character::clear_position() {
  position_.Clear();
}
inline const ::TLMP::NetworkMessages::Position& Character::position(int index) const {
  return position_.Get(index);
}
inline ::TLMP::NetworkMessages::Position* Character::mutable_position(int index) {
  return position_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Position* Character::add_position() {
  return position_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
Character::position() const {
  return position_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
Character::mutable_position() {
  return &position_;
}

// optional int32 id = 5;
inline bool Character::has_id() const {
  return _has_bit(4);
}
inline void Character::clear_id() {
  id_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 Character::id() const {
  return id_;
}
inline void Character::set_id(::google::protobuf::int32 value) {
  _set_bit(4);
  id_ = value;
}

// -------------------------------------------------------------------

// Equipment

// required int64 guid = 1;
inline bool Equipment::has_guid() const {
  return _has_bit(0);
}
inline void Equipment::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  _clear_bit(0);
}
inline ::google::protobuf::int64 Equipment::guid() const {
  return guid_;
}
inline void Equipment::set_guid(::google::protobuf::int64 value) {
  _set_bit(0);
  guid_ = value;
}

// optional int32 slot = 2;
inline bool Equipment::has_slot() const {
  return _has_bit(1);
}
inline void Equipment::clear_slot() {
  slot_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Equipment::slot() const {
  return slot_;
}
inline void Equipment::set_slot(::google::protobuf::int32 value) {
  _set_bit(1);
  slot_ = value;
}

// required int32 id = 3;
inline bool Equipment::has_id() const {
  return _has_bit(2);
}
inline void Equipment::clear_id() {
  id_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 Equipment::id() const {
  return id_;
}
inline void Equipment::set_id(::google::protobuf::int32 value) {
  _set_bit(2);
  id_ = value;
}

// -------------------------------------------------------------------

// Version

// required int32 version = 1;
inline bool Version::has_version() const {
  return _has_bit(0);
}
inline void Version::clear_version() {
  version_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Version::version() const {
  return version_;
}
inline void Version::set_version(::google::protobuf::int32 value) {
  _set_bit(0);
  version_ = value;
}

// -------------------------------------------------------------------

// GameHasStarted

// required bool started = 1;
inline bool GameHasStarted::has_started() const {
  return _has_bit(0);
}
inline void GameHasStarted::clear_started() {
  started_ = false;
  _clear_bit(0);
}
inline bool GameHasStarted::started() const {
  return started_;
}
inline void GameHasStarted::set_started(bool value) {
  _set_bit(0);
  started_ = value;
}

// -------------------------------------------------------------------

// GameStarted

// -------------------------------------------------------------------

// GameEnded

// -------------------------------------------------------------------

// GameEnter

// -------------------------------------------------------------------

// GameExited

// -------------------------------------------------------------------

// RequestCharacterInfo

// -------------------------------------------------------------------

// ReplyCharacterInfo

// repeated .TLMP.NetworkMessages.Character player = 1;
inline int ReplyCharacterInfo::player_size() const {
  return player_.size();
}
inline void ReplyCharacterInfo::clear_player() {
  player_.Clear();
}
inline const ::TLMP::NetworkMessages::Character& ReplyCharacterInfo::player(int index) const {
  return player_.Get(index);
}
inline ::TLMP::NetworkMessages::Character* ReplyCharacterInfo::mutable_player(int index) {
  return player_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Character* ReplyCharacterInfo::add_player() {
  return player_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >&
ReplyCharacterInfo::player() const {
  return player_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Character >*
ReplyCharacterInfo::mutable_player() {
  return &player_;
}

// -------------------------------------------------------------------

// ReplyCharacterId

// required int32 id = 1;
inline bool ReplyCharacterId::has_id() const {
  return _has_bit(0);
}
inline void ReplyCharacterId::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ReplyCharacterId::id() const {
  return id_;
}
inline void ReplyCharacterId::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// -------------------------------------------------------------------

// CharacterDestination

// required int32 id = 1;
inline bool CharacterDestination::has_id() const {
  return _has_bit(0);
}
inline void CharacterDestination::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 CharacterDestination::id() const {
  return id_;
}
inline void CharacterDestination::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// repeated .TLMP.NetworkMessages.Position current = 2;
inline int CharacterDestination::current_size() const {
  return current_.size();
}
inline void CharacterDestination::clear_current() {
  current_.Clear();
}
inline const ::TLMP::NetworkMessages::Position& CharacterDestination::current(int index) const {
  return current_.Get(index);
}
inline ::TLMP::NetworkMessages::Position* CharacterDestination::mutable_current(int index) {
  return current_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Position* CharacterDestination::add_current() {
  return current_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
CharacterDestination::current() const {
  return current_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
CharacterDestination::mutable_current() {
  return &current_;
}

// repeated .TLMP.NetworkMessages.Position destination = 3;
inline int CharacterDestination::destination_size() const {
  return destination_.size();
}
inline void CharacterDestination::clear_destination() {
  destination_.Clear();
}
inline const ::TLMP::NetworkMessages::Position& CharacterDestination::destination(int index) const {
  return destination_.Get(index);
}
inline ::TLMP::NetworkMessages::Position* CharacterDestination::mutable_destination(int index) {
  return destination_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Position* CharacterDestination::add_destination() {
  return destination_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
CharacterDestination::destination() const {
  return destination_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
CharacterDestination::mutable_destination() {
  return &destination_;
}

// -------------------------------------------------------------------

// Entity

// required int32 id = 1;
inline bool Entity::has_id() const {
  return _has_bit(0);
}
inline void Entity::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Entity::id() const {
  return id_;
}
inline void Entity::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required int32 level = 2;
inline bool Entity::has_level() const {
  return _has_bit(1);
}
inline void Entity::clear_level() {
  level_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 Entity::level() const {
  return level_;
}
inline void Entity::set_level(::google::protobuf::int32 value) {
  _set_bit(1);
  level_ = value;
}

// required int64 guid = 3;
inline bool Entity::has_guid() const {
  return _has_bit(2);
}
inline void Entity::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  _clear_bit(2);
}
inline ::google::protobuf::int64 Entity::guid() const {
  return guid_;
}
inline void Entity::set_guid(::google::protobuf::int64 value) {
  _set_bit(2);
  guid_ = value;
}

// required bool noItems = 4;
inline bool Entity::has_noitems() const {
  return _has_bit(3);
}
inline void Entity::clear_noitems() {
  noitems_ = false;
  _clear_bit(3);
}
inline bool Entity::noitems() const {
  return noitems_;
}
inline void Entity::set_noitems(bool value) {
  _set_bit(3);
  noitems_ = value;
}

// optional .TLMP.NetworkMessages.Position destination = 5;
inline bool Entity::has_destination() const {
  return _has_bit(4);
}
inline void Entity::clear_destination() {
  if (destination_ != NULL) destination_->::TLMP::NetworkMessages::Position::Clear();
  _clear_bit(4);
}
inline const ::TLMP::NetworkMessages::Position& Entity::destination() const {
  return destination_ != NULL ? *destination_ : *default_instance_->destination_;
}
inline ::TLMP::NetworkMessages::Position* Entity::mutable_destination() {
  _set_bit(4);
  if (destination_ == NULL) destination_ = new ::TLMP::NetworkMessages::Position;
  return destination_;
}

// repeated .TLMP.NetworkMessages.Position position = 6;
inline int Entity::position_size() const {
  return position_.size();
}
inline void Entity::clear_position() {
  position_.Clear();
}
inline const ::TLMP::NetworkMessages::Position& Entity::position(int index) const {
  return position_.Get(index);
}
inline ::TLMP::NetworkMessages::Position* Entity::mutable_position(int index) {
  return position_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Position* Entity::add_position() {
  return position_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
Entity::position() const {
  return position_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
Entity::mutable_position() {
  return &position_;
}

// -------------------------------------------------------------------

// Item

// required int32 id = 1;
inline bool Item::has_id() const {
  return _has_bit(0);
}
inline void Item::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 Item::id() const {
  return id_;
}
inline void Item::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required int64 guid = 2;
inline bool Item::has_guid() const {
  return _has_bit(1);
}
inline void Item::clear_guid() {
  guid_ = GOOGLE_LONGLONG(0);
  _clear_bit(1);
}
inline ::google::protobuf::int64 Item::guid() const {
  return guid_;
}
inline void Item::set_guid(::google::protobuf::int64 value) {
  _set_bit(1);
  guid_ = value;
}

// required int32 level = 3;
inline bool Item::has_level() const {
  return _has_bit(2);
}
inline void Item::clear_level() {
  level_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 Item::level() const {
  return level_;
}
inline void Item::set_level(::google::protobuf::int32 value) {
  _set_bit(2);
  level_ = value;
}

// required int32 unk0 = 4;
inline bool Item::has_unk0() const {
  return _has_bit(3);
}
inline void Item::clear_unk0() {
  unk0_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 Item::unk0() const {
  return unk0_;
}
inline void Item::set_unk0(::google::protobuf::int32 value) {
  _set_bit(3);
  unk0_ = value;
}

// required int32 unk1 = 5;
inline bool Item::has_unk1() const {
  return _has_bit(4);
}
inline void Item::clear_unk1() {
  unk1_ = 0;
  _clear_bit(4);
}
inline ::google::protobuf::int32 Item::unk1() const {
  return unk1_;
}
inline void Item::set_unk1(::google::protobuf::int32 value) {
  _set_bit(4);
  unk1_ = value;
}

// -------------------------------------------------------------------

// ItemDrop

// required int32 id = 1;
inline bool ItemDrop::has_id() const {
  return _has_bit(0);
}
inline void ItemDrop::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ItemDrop::id() const {
  return id_;
}
inline void ItemDrop::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// repeated .TLMP.NetworkMessages.Position position = 2;
inline int ItemDrop::position_size() const {
  return position_.size();
}
inline void ItemDrop::clear_position() {
  position_.Clear();
}
inline const ::TLMP::NetworkMessages::Position& ItemDrop::position(int index) const {
  return position_.Get(index);
}
inline ::TLMP::NetworkMessages::Position* ItemDrop::mutable_position(int index) {
  return position_.Mutable(index);
}
inline ::TLMP::NetworkMessages::Position* ItemDrop::add_position() {
  return position_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >&
ItemDrop::position() const {
  return position_;
}
inline ::google::protobuf::RepeatedPtrField< ::TLMP::NetworkMessages::Position >*
ItemDrop::mutable_position() {
  return &position_;
}

// required bool unk0 = 3;
inline bool ItemDrop::has_unk0() const {
  return _has_bit(2);
}
inline void ItemDrop::clear_unk0() {
  unk0_ = false;
  _clear_bit(2);
}
inline bool ItemDrop::unk0() const {
  return unk0_;
}
inline void ItemDrop::set_unk0(bool value) {
  _set_bit(2);
  unk0_ = value;
}

// -------------------------------------------------------------------

// ItemPickup

// required int32 id = 1;
inline bool ItemPickup::has_id() const {
  return _has_bit(0);
}
inline void ItemPickup::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ItemPickup::id() const {
  return id_;
}
inline void ItemPickup::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required int32 ownerId = 2;
inline bool ItemPickup::has_ownerid() const {
  return _has_bit(1);
}
inline void ItemPickup::clear_ownerid() {
  ownerid_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 ItemPickup::ownerid() const {
  return ownerid_;
}
inline void ItemPickup::set_ownerid(::google::protobuf::int32 value) {
  _set_bit(1);
  ownerid_ = value;
}

// -------------------------------------------------------------------

// ItemEquip

// required int32 id = 1;
inline bool ItemEquip::has_id() const {
  return _has_bit(0);
}
inline void ItemEquip::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ItemEquip::id() const {
  return id_;
}
inline void ItemEquip::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required int32 slot = 2;
inline bool ItemEquip::has_slot() const {
  return _has_bit(1);
}
inline void ItemEquip::clear_slot() {
  slot_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 ItemEquip::slot() const {
  return slot_;
}
inline void ItemEquip::set_slot(::google::protobuf::int32 value) {
  _set_bit(1);
  slot_ = value;
}

// required int32 ownerId = 3;
inline bool ItemEquip::has_ownerid() const {
  return _has_bit(2);
}
inline void ItemEquip::clear_ownerid() {
  ownerid_ = 0;
  _clear_bit(2);
}
inline ::google::protobuf::int32 ItemEquip::ownerid() const {
  return ownerid_;
}
inline void ItemEquip::set_ownerid(::google::protobuf::int32 value) {
  _set_bit(2);
  ownerid_ = value;
}

// required int32 unk = 4;
inline bool ItemEquip::has_unk() const {
  return _has_bit(3);
}
inline void ItemEquip::clear_unk() {
  unk_ = 0;
  _clear_bit(3);
}
inline ::google::protobuf::int32 ItemEquip::unk() const {
  return unk_;
}
inline void ItemEquip::set_unk(::google::protobuf::int32 value) {
  _set_bit(3);
  unk_ = value;
}

// -------------------------------------------------------------------

// ItemUnequip

// required int32 id = 1;
inline bool ItemUnequip::has_id() const {
  return _has_bit(0);
}
inline void ItemUnequip::clear_id() {
  id_ = 0;
  _clear_bit(0);
}
inline ::google::protobuf::int32 ItemUnequip::id() const {
  return id_;
}
inline void ItemUnequip::set_id(::google::protobuf::int32 value) {
  _set_bit(0);
  id_ = value;
}

// required int32 ownerid = 2;
inline bool ItemUnequip::has_ownerid() const {
  return _has_bit(1);
}
inline void ItemUnequip::clear_ownerid() {
  ownerid_ = 0;
  _clear_bit(1);
}
inline ::google::protobuf::int32 ItemUnequip::ownerid() const {
  return ownerid_;
}
inline void ItemUnequip::set_ownerid(::google::protobuf::int32 value) {
  _set_bit(1);
  ownerid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace NetworkMessages
}  // namespace TLMP

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_network_2eproto__INCLUDED
